name: elections-models
channels:
  - conda-forge
dependencies:
  - aesara>=2.0.9
  - arviz>=0.11.2
  - black
  - bokeh
  - dill
  - fiona
  - geopandas
  - jupyterlab
  - libblas=*=*mkl
  - lxml
  - matplotlib
  - mkl-service
  - numpy
  - openpyxl
  - pandas
  - pip
  - python-graphviz
  - scipy
  - shapely
  - watermark
  - xlrd
  - pip:
      - git+https://github.com/pymc-devs/pymc3